apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencut.fullname" . }}-config
  labels:
    {{- include "opencut.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_SITE_URL: {{ .Values.config.nextPublicSiteUrl | quote }}
  NEXT_PUBLIC_MARBLE_API_URL: {{ .Values.config.nextPublicMarbleApiUrl | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  UPSTASH_REDIS_REST_URL: {{ printf "http://%s-srh:80" (include "opencut.fullname" .) | quote }}
