apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencut.fullname" . }}-secrets
  labels:
    {{- include "opencut.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | b64enc | quote }}
  SRH_TOKEN: {{ .Values.secrets.srhToken | b64enc | quote }}
  FREESOUND_CLIENT_ID: {{ .Values.secrets.freesoundClientId | b64enc | quote }}
  FREESOUND_API_KEY: {{ .Values.secrets.freesoundApiKey | b64enc | quote }}
  MARBLE_WORKSPACE_KEY: {{ .Values.secrets.marbleWorkspaceKey | b64enc | quote }}
